service: sweet-sensei

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    CLIENT_URL: ${env:CLIENT_URL}
  httpApi:
    cors: true
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - !GetAtt UsersTable.Arn
            - !GetAtt ProductsTable.Arn
            - !GetAtt OrdersTable.Arn
            - !Join
              - '/'
              - - !GetAtt UsersTable.Arn
                - 'index'
                - 'EmailIndex'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    define:
      'require.resolve': undefined
    platform: 'node'
    concurrency: 10

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/**'
    - '!node_modules/@prisma/**'
    - '!tests/**'

functions:
  signup:
    handler: src/functions/users.signup
    events:
      - http:
          path: /users
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false
  login:
    handler: src/functions/users.login
    events:
      - http:
          path: /users/login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false
  addProduct:
    handler: src/functions/products.addProduct
    events:
      - http:
          path: /products
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false
  getProducts:
    handler: src/functions/products.getProducts
    events:
      - http:
          path: /products
          method: get
  getProduct:
    handler: src/functions/products.getProduct
    events:
      - http:
          path: /products/{id}
          method: get
  createCheckoutSession:
    handler: src/functions/orders.createStripeSession
    events:
      - http:
          path: /orders/create-stripe-checkout-session
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false
  addAddress:
    handler: src/functions/users.addAddress
    events:
      - http:
          path: /users/addresses
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false
  getAddress:
    handler: src/functions/users.getAddress
    events:
      - http:
          path: /users/addresses
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - GET
              - OPTIONS
            allowCredentials: false
  upgradeToPartner:
    handler: src/functions/users.upgradeToPartner
    events:
      - http:
          path: /users/partners
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false
  changePassword:
    handler: src/functions/users.changePassword
    events:
      - http:
          path: /users/change-password
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - PUT
              - OPTIONS
            allowCredentials: false
  completeOrder:
    handler: src/functions/orders.completeOrder
    events:
      - http:
          path: /orders/pay/complete
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - POST
              - OPTIONS
            allowCredentials: false

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: partnerCode
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: PartnerCodeIndex
            KeySchema:
              - AttributeName: partnerCode
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-orders
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH 